;
; task10
;
; Created: 08/03/2017 17:00:00
; Author : Mathieu Petitjean

.include "m328pdef.inc"

;------------
; CONSTANTS 
;------------

;SCREEN
.equ SCREEN_DDR		= DDRB
.equ SCREEN_PORT	= PORTB
.equ SCREEN_PIN		= PINB
.equ SCREEN_DATA	= 3
.equ SCREEN_CLK		= 5

;TCNT 1 RESET VALUE
.equ TCNT1_RESET_880	= 47354
.equ TCNT1_RESET_1760	= 56444


;--------
; MACROS
;--------

;-------
; CODE 
;-------
.CSEG
.ORG 0x0000
rjmp init

init:
	; Set PB3,4,5 as output
	; Set them at LOW
	LDI r17, (1<<3)|(1<<4)|(1<<5)
	OUT SCREEN_PORT, r17
	OUT SCREEN_DDR, r17

	RJMP main

main:
	; loop for 80 columns
	;LDI ZH, high(CharacterA<<1) ; Initialize Z pointer for column conf
	LDI ZL, low(CharacterA<<1)
	LDI r16, 0x07
	LDI r21, 0b100000
	loop:
		LPM r1, Z+
		LDI r18,0x10
		columns:
			SBI SCREEN_PORT, SCREEN_DATA
			SBRS r1,0
			CBI SCREEN_PORT, SCREEN_DATA
			SBI SCREEN_PIN,SCREEN_CLK
			SBI SCREEN_PIN,SCREEN_CLK

			SBI SCREEN_PORT, SCREEN_DATA
			SBRS r1,1
			CBI SCREEN_PORT, SCREEN_DATA
			SBI SCREEN_PIN,SCREEN_CLK
			SBI SCREEN_PIN,SCREEN_CLK
			
			SBI SCREEN_PORT, SCREEN_DATA
			SBRS r1,2
			CBI SCREEN_PORT, SCREEN_DATA
			SBI SCREEN_PIN,SCREEN_CLK
			SBI SCREEN_PIN,SCREEN_CLK
			
			SBI SCREEN_PORT, SCREEN_DATA
			SBRS r1,3
			CBI SCREEN_PORT, SCREEN_DATA
			SBI SCREEN_PIN,SCREEN_CLK
			SBI SCREEN_PIN,SCREEN_CLK
			
			SBI SCREEN_PORT, SCREEN_DATA
			SBRS r1,4
			CBI SCREEN_PORT, SCREEN_DATA
			SBI SCREEN_PIN,SCREEN_CLK
			SBI SCREEN_PIN,SCREEN_CLK
			
			DEC r18
			BRNE columns 
		
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK

		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,0
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,1
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,2
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,3
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,4
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,5
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		SBI SCREEN_PORT, SCREEN_DATA
		SBRS r21,6
		CBI SCREEN_PORT,SCREEN_DATA
		SBI SCREEN_PIN,SCREEN_CLK
		SBI SCREEN_PIN,SCREEN_CLK
		
		LSR r21

		; set PB4 HIGH, wait 100 µs
		SBI SCREEN_PIN,4

		; Finite loop - wait
		LDI R17,0xFF
		MyLoop: 
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			NOP
			DEC R17
			BRNE MyLoop
		SBI SCREEN_PIN,4
		DEC r16
		BRNE mustloop

	RJMP main

mustloop:
	RJMP loop

CharacterA: 
	.db 0b11111, 0b10001, 0b10001, 0b11111, 0b10001, 0b10001, 0b10001, 0